
## Application Name and Title

appname: "StuffTracker"
program_title: "Stuff Tracker"

## Database Info

db: "/home/starman/db/StuffTracker.db"

## Authentication Database Info

db_auth: "/home/starman/db/UserManager.db"

###############################################################################

dbi_to_use: "SQLite"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "simple"

# template: "template_toolkit"
# engines:
#   template:
#     template_toolkit:
#       start_tag: '<%'
#       end_tag:   '%>'

session: "YAML"

engines:
  session:
    YAML:
      session_dir: "/home/starman/sessions"
